title: "Alex Mudge â€” Data Engineering"
description: "Production-like data engineering builds, explained clearly."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Alex Mudge"
github_username: "notmudge"
exclude:
  - "README.md"
